### ISSUE TITLE
Injecting dependencies into Systems

### ISSUE THREAD

**Issue by brunocapdevila** [LastOliveGames/becsy#24]
Hello,

I've been studying Becsy for a few days and it has super interesting concepts. Nice library!
But I am wondering how would you approach the need of passing dependencies into systems.
They are currently automatically constructed so one cannot define construction parameters.

One example that comes into mind is a PixiRenderSystem that takes the Pixi.application as construction parameter.
Maybe we want to inject a canvas 2d object so that we can draw gizmos as an overlay to debug our game.
I think it is a very common use case.

Does anything need to be represented as an entity+component to be accessed by a system ?

**Comment by pkaminski** [comment]
Hey Bruno, thanks for checking out Becsy!  While you can't take parameters through the constructor, you can inject external dependencies into systems via the world's defs:  see [this section of the docs](https://lastolivegames.github.io/becsy/guide/architecture/systems.html#defining-systems).

No worries about being inexperienced -- I tried diving into Unity a few years ago and had similar basic questions for things that just didn't make sense to me.  :)
