### ISSUE TITLE
Example demo, teypscript version reports error, cannot find attribute `track` on `QueryBuilder`

### ISSUE THREAD

**Issue by yocover** [LastOliveGames/becsy#25]
`this.query(q => q.addedOrChanged.with(DOMRenderable).and.with(Position).track);`
Example demo, teypscript version reports error, cannot find attribute `track` on `QueryBuilder`

**Comment by pkaminski** [comment]
The examples were still built against an older version of Becsy — sorry about that.  I upgraded everything to the latest version.
