### ISSUE TITLE
why use sparse set rather than archetype?

### ISSUE THREAD

**Issue by yafacex** [LastOliveGames/becsy#26]
I'm new to ecs.Why use sparse set rather than archetype?I dont know the benefit of sparse set.

**Comment by pkaminski** [comment]
I think you can find plenty of articles on the trade-offs between the two architectures.  For Becsy in particular, I wanted all the data structures to be compatible with a lockless multithreading strategy and saw a clear way forward with sparse sets so just went with that.  That's not to say that you couldn't do it with archetypes too but I just didn't see how.
