### ISSUE TITLE
"Should commit log maxShapeChangesPerFrame before counting" - Bug report

### ISSUE THREAD

**Issue by J3F31** [LastOliveGames/becsy#30]
![image](https://github.com/user-attachments/assets/b2b1d05d-9e06-41c4-9494-de596ce43e71)

**Comment by pkaminski** [comment]
Sorry, I saw this on the Discord but won't have time to look into it until sometime this weekend.  Does it repro consistently by any chance?

**Comment by J3F31** [comment]
No worries. Yes, it appears every time I create many entities at once.

**Comment by pkaminski** [comment]
Can you put a number on that, as well as your log sizes?  It'll be a lot easier to fix if I can repro in a test.

**Comment by J3F31** [comment]
I looked into this a bit more. Apparently it's not about the amount of entities created.
So I have an async function with a callback and I'm awaiting some font loads before the callback.
I'm then doing some ecs operations on the callback.

Something like this:
`import {System} from "@lastolivegames/becsy";
import {BugRepro1} from "../components/bug-repro-1";
import {BugRepro2} from "../components/bug-repro-2";

export class BugReproSystem extends System {
    #entities = this.query(q => q.added.with(BugRepro1).write.using(BugRepro2).write)
    
    initialize() {
        this.createEntity(BugRepro1, BugRepro2)
        this.createEntity(BugRepro1, BugRepro2)
        this.createEntity(BugRepro1, BugRepro2)
    }

    execute() {
        for (const entity of this.#entities.added) {
            const entityHold = entity.hold()
            this.#testCallback('callback', (log) => {
                entityHold.write(BugRepro1).type = log
                entityHold.remove(BugRepro2)
                this.createEntity(BugRepro2)
                console.log(entityHold.read(BugRepro1).type)
            })
        }
    }
    
    async #testCallback(log, callback) {
        const fontLoadPromises = []
        for (const font of document.fonts) {
            if (font.status === 'unloaded') fontLoadPromises.push(font.load())
            else if (font.status === 'loading') fontLoadPromises.push(font.loaded)
        }
        await Promise.all(fontLoadPromises)
        callback(log)
    }
}`

I tried to recreate it on another project but the error would not show up.
I did some testing and here are some cases I found:
Error doesn't show when...
- Callback function doesn't await for anything
- Only doing a write operation in the callback (no add/remove or create)

Nothing is breaking, this is not a pressing matter.

**Comment by J3F31** [comment]
Ah, I see. Thanks for your time.
I got a bit confused initially as I was writing to a component in the async callback and no error was being thrown.
I'll move my async stuff into `prepare`.
